name: topomodels
version: 0.1.0.0
synopsis: TODO
description: TODO
maintainer:
  - David Quinn Alvarez <dqalvarez@proton.me>
  - Paulius Skaisgiris <paulius.skaisgiris@gmail.com>
category: Logic

ghc-options: -Wall

dependencies:
  - base
  - random
  - QuickCheck
  - containers
  - hspec
  - time

library:
  source-dirs: lib

tests:
  tests:
    main: tests.lhs
    source-dirs: test
    dependencies:
      - topomodels
      - QuickCheck
      - hspec

benchmarks:
  bench-BenchFormulaSatisfaction:
    source-dirs: bench
    main: BenchFormulaSatisfaction.hs
    ghc-options:  -main-is BenchFormulaSatisfaction
    dependencies:
      - base
      - topomodels
      - time

  bench-BenchModelConversion:
    source-dirs: bench
    main: BenchModelConversion.hs
    ghc-options:  -main-is BenchModelConversion
    dependencies:
      - base
      - topomodels
      - time

  bench-BenchModelGeneration:
    source-dirs: bench
    main: BenchModelGeneration.hs
    ghc-options:  -main-is BenchModelGeneration
    dependencies:
      - base
      - topomodels
      - time