name: topomodels
version: 0.1.0.0
synopsis: TODO
description: TODO
maintainer:
  - David Alvarez Lombardi <dqalombardi@proton.me>
  - Paulius Skaisgiris <paulius.skaisgiris@gmail.com>
category: Logic

ghc-options: -Wall

dependencies:
  - base
  - random
  - QuickCheck
  - containers

library:
  source-dirs: lib

executables:
  myprogram:
    main: Main.lhs
    source-dirs: exec
    dependencies:
      - topomodels

tests:
  tests:
    main: tests.lhs
    source-dirs: test
    dependencies:
      - topomodels
      - QuickCheck
      - hspec
