name: topomodels
version: 0.1.0.0
synopsis: My Haskell project
description: See topomodels.pdf
maintainer: My Name <my.email@example.com>
category: Logic

ghc-options: -Wall

dependencies:
  - base
  - random
  - QuickCheck

library:
  source-dirs: lib

executables:
  myprogram:
    main: Main.lhs
    source-dirs: exec
    dependencies:
      - topomodels

tests:
  simpletests:
    main: simpletests.lhs
    source-dirs: test
    dependencies:
      - topomodels
      - QuickCheck
      - hspec
