name: topomodels
version: 0.1.0.0
synopsis: TODO
description: TODO
maintainer:
  - David Quinn Alvarez <dqalombardi@proton.me>
  - Paulius Skaisgiris <paulius.skaisgiris@gmail.com>
  - Djanira dos Santos Gomes <djaniradsgomes@gmail.com>
category: Logic

ghc-options: -Wall

dependencies:
  - base
  - random
  - QuickCheck
  - containers
  - graphviz
  - hspec
  - smcdel
  - decision-diagrams
  - directory
  - process
  - tagged
  - time
  - unordered-containers

library:
  source-dirs: lib

tests:
  tests:
    main: tests.hs
    source-dirs: test
    dependencies:
      - topomodels
      - QuickCheck
      - hspec

benchmarks:
  cake:
    source-dirs: bench
    main: cake.hs
    dependencies:
      - base
      - topomodels
      - criterion
      - time
      - bytestring
      - cassava
      - scientific
      - vector
      - split